server:
  port: 9000
  servlet:
    context-path: /api/v1/library
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/${MSQL_DATABASE}
    username: root
    password: ${MSQL_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 2000000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${application.email}
    password: ${EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


eureka:
  #  instance:
  #    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
application:
  name: library - user service
  version: 0.1.0
  developer: caito Vilas
  email: caitocd@gmail.com