server:
  port: 8761
spring:
  application:
    name: discovery-server
eureka:
  client:
        registerWithEureka: false
        fetchRegistry: false
application:
  name: library management - dicovery server
  version: 0.1.0
  developer: caito VIlas
